### PR TITLE
implement captain workflow

### PR DESCRIPTION
**Pull request by slajax**
#### overview

new projects should be setup to use [captain](https://github.com/harbur/captain) by default

#### tasks

- [x] leverage [captain](https://github.com/harbur/captain) 
- [x] captain.yml
- [x] Dockerfile.test
- [x] update package.json
- [x] add yarn to docker build

### CODE REVIEW

**Comment by slajax** [comment]
@eddyystop this is ready for review now if you want to check it out :)

**Comment by slajax** [comment]
Couple other ideas:

- [ ] npm run docker (simply starts docker)
- [ ] Dockerfile.test extends Dockerfile
- [ ] hook into npm run release:*

**Comment by eddyystop** [comment]
Unfortunately I don't have enough background to check it out. :(

**Comment by slajax** [comment]
@eddyystop no problem! I'll merge it cause I tested it, just wanted to give you the opportunity since you said you were looking forward to it.

**Comment by eddyystop** [comment]
Looking forward to see how *you* do it !

**Comment by marshallswain** [comment]
Haha.  Me, too!

**Comment by ekryski** [comment]
Oh nice!

**Pull request merged**
